diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=dilgr6.rictu@gmail.com
user.name=rictu6
color.ui=auto
gui.recentrepo=C:/laragon/www/DILG_Newest
http.sslverify=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url="https://github.com/rictu6/DILG_Newest.git"
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
gui.wmstate=normal
gui.geometry=1109x563+192+192 216 255
lfs.repositoryformatversion=0
remote.origin1.url=https://github.com/rictu6/DILG_Newest.git
remote.origin1.fetch=+refs/heads/*:refs/remotes/origin1/*
remote.origin2.url=https://github.com/rictu6/DILG_Newest.git
remote.origin2.fetch=+refs/heads/*:refs/remotes/origin2/*
